# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ef2e0859eb95de1c851a24bb7eae91991ad0f51b302cac34d26d6a96b967306b7140dd097064aee3995f67695a676d59bc0f0ea2525e284b7ad72d6575d56b0

test:
  secret_key_base: 2c34b9a234899ee1f19fd5e3835798f733c97457a904c9bb9a0d92cfe2b01a4f28d5bfbdd04c850a39c8c3db3df162d9de3053e01cb04b7c4e4daed895908cab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
